### ISSUE TITLE
`messageBodySchema` could contain `meta.description`

### ISSUE THREAD

**Issue by freaz** [apiaryio/fury-adapter-swagger#10]
Description for JSON Schema is omitted.

https://github.com/apiaryio/swagger-zoo/blob/master/fixtures/features/swagger/param-no-response.yaml

**Comment by pksunkara** [comment]
@freaz Can you please explain this a bit more? Thanks.

**Comment by freaz** [comment]
@pksunkara Sorry for brief description:

Parameter description https://github.com/apiaryio/swagger-zoo/blob/master/fixtures/features/swagger/param-no-response.yaml#L8 isn't present in genererated json schema https://github.com/apiaryio/swagger-zoo/blob/master/fixtures/features/refract/param-no-response.json#L49

**Comment by pksunkara** [comment]
MSON generation would have been great in here.

**Comment by kylef** [comment]
JSON Schemas are generated including the *schhema* description:

For example:

```yaml
schema:
  type: string
  description: schema desc
```

```json
{ "content": "{\"type\":\"string\",\"description\":\"schema desc\"}" }
```
