### ISSUE TITLE
refract fixture `produces-header` doesn't contain any header entries

### ISSUE THREAD

**Issue by freaz** [apiaryio/fury-adapter-swagger#11]
It seems that we have wrong refract fixture for swagger:
https://github.com/apiaryio/fury-adapter-swagger/blob/master/test/fixtures/swagger/produces-header.yaml

And refract result:
https://github.com/apiaryio/fury-adapter-swagger/blob/master/test/fixtures/refract/produces-header.json

Which probably means also bug in adapter.

**Comment by kylef** [comment]
Looks like this has been fixed, the fixture has produced headers: https://github.com/apiaryio/swagger-zoo/blob/43ef7aca94baa77188886dfd779d309f8735ff9c/fixtures/features/api-elements/produces-header.json#L77
