### ISSUE TITLE
Default response is omitted

### ISSUE THREAD

**Issue by freaz** [apiaryio/fury-adapter-swagger#13]
https://github.com/apiaryio/swagger-zoo/blob/master/fixtures/features/swagger/default-response.yaml

**Comment by pksunkara** [comment]
This was supposed to be intentional if I remember. @danielgtaylor or @smizell would know more.

**Comment by danielgtaylor** [comment]
We deliberately ignore the default response because I'm not sure how it should be represented. In Swagger you would return it for *any* type of response that isn't explicitly listed but in Refract we expect every possible response to be listed explicitly. We need to figure out what to do with this.

**Comment by erajkovic** [comment]
If you are talking about this warning in the fury tool: warning: (3)  Default response is not yet supported
Then yes, we need to figure a way to support this as it's becoming a common pattern when you have larger Swagger documents.
The main benefit I see, as a Swagger author is that I do not have to cover '500', '502', '503', and a bunch of 3xx / 4xx error codes as well - They are mostly related to the proxy layers before to reach my application code layer.
Concrete Swagger file for a sample: https://apicatalog.oraclecloud.com/public/v1/orgs/oracle-public/apicollections/apicatalog/1.0/apis/API%20Collections/canonical

**Comment by kylef** [comment]
Moved to https://github.com/apiaryio/api-elements.js/issues/264
