### ISSUE TITLE
Circular references in schema are not yet supported

### ISSUE THREAD

**Issue by erajkovic** [apiaryio/fury-adapter-swagger#178]
We should find a way to add support for circular references.

current output:
warning: (3)  Circular references in schema are not yet supported

Here are some Swagger documents that will expose this current limitation:
https://apicatalog.oraclecloud.com/public/v1/orgs/oracle-public/apicollections/apicatalog/1.0/apis/API%20Collections/canonical
https://apicatalog.oraclecloud.com/public/v1/orgs/oracle-public/apicollections/commerce/17.4/apis/webhooks/canonical

**Comment by kylef** [comment]
Circular references have been supported for a little while, I've forgotten to close this issue.
