### ISSUE TITLE
tonic-example.js not working for me

### ISSUE THREAD

**Issue by erajkovic** [apiaryio/fury-adapter-swagger#181]
Should the code in tonic-example.js be updated to match the doc?
Alternate option would be to remove the reference from the README and the broken sample.

see  https://tonicdev.com/npm/fury-adapter-swagger

  if (err) {
    console.log(err);
    return;
  }

  // The returned `result` is a Minim parse result element.
  console.log(result.api.title);

**Comment by kylef** [comment]
We've moved this project to http://github.com/apiaryio/api-elements.js and in the process we've removed this incorrect tonic-example.js.
