### ISSUE TITLE
The date-time format doesn't allow timezone offset

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/fury-adapter-swagger#191]
Filing this on behalf of @erajkovic. It seems the `date-time` format treats strings containing the timezone offset as invalid. The [Swagger 2.0 spec](https://swagger.io/specification/v2/#data-types) mentions RFC3339 and links to [this page](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14) where I can see timezone offsets in the grammar. Thus I assume this is a bug in the Fury adapter.

**Comment by pksunkara** [comment]
@honzajavorek What's the bug? Are you saying the adapter is not parsing it? Or it is not generating it correctly. Is there a related issue I can look at to understand it more?

**Comment by honzajavorek** [comment]
It seems like the adapter generates following RegExp as a validation rule for the value when the format is `date-time`:

```js
/^\d{4}-(?:0[0-9]{1}|1[0-2]{1})-[0-9]{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/
```

However, the `date-time` spec allows values like this:

```
2018-05-25T15:39:38.12-07:00
```

So this is a bug. The RegExp needs to be modified to allow also timezone offsets.

**Comment by kylef** [comment]
@honzajavorek Could you perhaps provide an example Swagger document that can reproduce, I tried with parameters using both x-example and default value validation and the document parses without warnings:

```yaml
swagger: '2.0'
info:
  version: '1.0'
  title: "test"
paths:
  /:
    parameters:
      - name: since
        in: query
        type: string
        format: date-time
        x-example: '2018-05-25T15:39:38.12-07:00'
    get:
      summary: Example
      responses:
        200:
          description: Example
          schema:
            type: array
```

**Comment by pksunkara** [comment]
> adapter generates following RegExp as a validation rule

IIRC We don't generate the rule anywhere. Maybe I am just misunderstanding what you are saying.

**Comment by honzajavorek** [comment]
Hmmm 🤔 Let me investigate further then.

**Comment by honzajavorek** [comment]
I found the issue 😮

https://github.com/apiaryio/Amanda/blob/master/src/engines/json/attributes/format.js#L22

**Comment by honzajavorek** [comment]
Fixing by https://github.com/apiaryio/Amanda/pull/9
