### ISSUE TITLE
Swagger serializer support

### ISSUE THREAD

**Issue by vine77** [apiaryio/fury-adapter-swagger#41]
@danielgtaylor, Is there any plan to create a fury-adapter-swagger-serializer so that an API Blueprint could be converted to Swagger/OpenAPI Specification?

P.S. I'm happy to hear about the [announcement](http://blog.apiary.io/2016/01/18/We-ve-got-Swagger/) of Swagger support in Apiary.

**Comment by danielgtaylor** [comment]
@vine77 there is currently no plan to add a Swagger / OpenAPI serializer to this module or to create a new module for it. That said, I would happily merge or support such a project however I can if someone else wants to do it!

**Comment by kylef** [comment]
https://github.com/apiaryio/api-elements.js/issues/46 is tracking this idea.
