### ISSUE TITLE
Changelog is out of date

### ISSUE THREAD

**Issue by danielgtaylor** [apiaryio/fury-adapter-swagger#60]
Looks like the [Changelog](https://github.com/apiaryio/fury-adapter-swagger/blob/master/Changelog.md) hasn't been updated in a while. It's hard to tell what the 0.8.x releases have changed.

Since this is a public-facing project and we expect people to use the API Elements output I strongly suggest we keep the changelog going. :+1:

**Comment by kylef** [comment]
I think this has been resolved https://github.com/apiaryio/fury-adapter-swagger/blob/master/Changelog.md#080---2016-07-01

Please let me know if you noticed something we missed.
