### ISSUE TITLE
Message body generator produces invalid API Elements output

### ISSUE THREAD

**Issue by danielgtaylor** [apiaryio/fury-adapter-swagger#61]
As reported in this [Trello card](https://trello.com/c/0vBs8g7R/114-fury-swagger-adapter-or-metamorphoses-doesn-t-stringify-response-bodies), sometimes an object will be given as a request/response body instead of a string, which can screw with the documentation, mock server, etc. I believe I have traced this back to the Swagger adapter. First, here is a sample minimal valid input document:

```yaml
swagger: "2.0"
info:
  version: 1.0.0
  title: Body Test
  description: A test to see how bodies get parsed / created
host: example.com
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /resource:
    get:
      description: Get a resource
      operationId: getResource
      responses:
        200:
          description: response description
          schema:
            example:
              id: 123
              name: Resource 1
```

Note that no response example is given directly. Instead, an example is set in the JSON Schema. Using the [Fury Swagger Adapter 0.8.0-pre.12 in Tonic](https://tonicdev.com/danielgtaylor/fury-adapter-swagger-bad-message-body) you get the following output excerpt:

```json
{
  "element": "asset",
  "meta": {
    "classes": [
      "messageBody"
    ],
    "links": [
      {
        "element": "link",
        "meta": {},
        "attributes": {
          "relation": "inferred",
          "href": "http://docs.apiary.io/validations/swagger#message-body-generation"
        },
        "content": []
      }
    ]
  },
  "attributes": {
    "contentType": "application/json"
  },
  "content": {
    "id": 123,
    "name": "Resource 1"
  }
},
```

This (inferred message body generation from JSON Schema) is apparently a new (and neat) feature. The problem I am having is that it is not [spec-compliant with API Elements and wreaks havoc downstream. The problematic part is the `content` of the asset, which is an `object` instead of `string`.

API Elements defines an `Asset` as having a `content` that [**must** be a string](http://api-elements.readthedocs.io/en/latest/element-definitions/#asset-base-api-element). The code should probably be updated to stringify the body similar to [this existing code](https://github.com/apiaryio/fury-adapter-swagger/blob/master/src/parser.js#L620-L622).

**Comment by pksunkara** [comment]
Ah. JSON.stringifying it should fix it.

**Comment by kuba-kubula** [comment]
@pksunkara Also please get that release into Apiary ASAP.
It already was causing some mock-server / documentation related issues. (and incidents).
