### ISSUE TITLE
Content-Type header of Swagger response needs to override anything else 

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/fury-adapter-swagger#65]
Response's `Content-Type` header should override any `produces`. Example:

```yaml
swagger: "2.0"
info:
  version: "1.0"
  title: Beehive API
consumes:
  - application/json
produces:
  - application/json
paths:
  /honey:
    get:
      responses:
        400:
          description: user error
        500:
          description: server error
        200:
          description: pet response
          headers:
            Content-Type: text/plain
            X-Test:
              type: string
              enum:
                - Adam
                - Pavan
          schema:
            $ref: '#/definitions/Bee'
...
```

Expected behavior is that the response will have `Content-Type` set to `text/plain`.

**Comment by honzajavorek** [comment]
Please update the note paragraph [here](https://github.com/apiaryio/dredd/blob/master/docs/how-it-works.md#response-headers-expectations) once fixed.

**Comment by pksunkara** [comment]
```yaml
Content-Type: text/plain
```

is not valid. Each header is always a schema.

**Comment by pksunkara** [comment]
@honzajavorek Are you sure about this issue? Because I already see the override.

**Comment by joeSaad** [comment]
Is there a way to do the opposite, basically override swagger content types from within either my swagger specs or my application?

**Comment by pksunkara** [comment]
@joeSaad What do you mean by your question? Can you explain a bit more? Thanks.
