### ISSUE TITLE
"in": "formData" parameters should generate body assets and application/x-www-form-urlencoded content type

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/fury-adapter-swagger#67]
We should add support for
- urlencoded body assets generated from `"in": "formData"` parameters
- inferred `Content-Type` header `application/x-www-form-urlencoded` for the request

Out of scope now (should give warnings):
- path-level `formData` parameters are not supported
- arrays and `collectionFormat`
- `file` type parameter
- `allowEmptyValue`

**Comment by honzajavorek** [comment]
Please update the note paragraph [here](https://github.com/apiaryio/dredd/blob/master/docs/how-it-works.md#request-headers) once fixed.

**Comment by pksunkara** [comment]
@honzajavorek This has been supported for a long time.

**Comment by pksunkara** [comment]
Shouldn't we close this?

**Comment by pksunkara** [comment]
> inferred Content-Type header application/x-www-form-urlencoded for the request

That is wrong. Swagger specifies that you need that in the consumes for the formData to be valid.

**Comment by honzajavorek** [comment]
@pksunkara You are right, this should be already closed.
