### ISSUE TITLE
Parameters are skipped

### ISSUE THREAD

**Issue by freaz** [apiaryio/fury-adapter-swagger#9]

**Comment by smizell** [comment]
Would you care to provide additional information on this?

**Comment by freaz** [comment]
Yes sure, I just added to not forget about it.

**Comment by smizell** [comment]
Sounds good :)

**Comment by freaz** [comment]
OK closing because it was about [x-ingnored](https://github.com/apiaryio/fury-adapter-swagger/blob/master/test/fixtures/swagger/extensions.yaml) extensions which is ignored purposely.
