### ISSUE TITLE
Having multipart/form-data is generating urlencoded data

### ISSUE THREAD

**Issue by pksunkara** [apiaryio/fury-adapter-swagger#96]
Given the following swagger document, even though the consumes mentions `multipart/form-data`, the generated request asset has content type `application/x-www-form-urlencoded` and url encoded data which is not what the user is requesting.

```yaml
swagger: '2.0'
info:
  title: Form Data
  version: '1.0'
consumes:
  - multipart/form-data
paths:
  '/test':
    post:
      parameters:
        - name: name
          in: formData
          required: true
          type: string
      responses:
        200:
          description: 'My Response'
```

**Comment by pksunkara** [comment]
This is also kinda related to #67.

**Comment by honzajavorek** [comment]
In my opinion, `application/x-www-form-urlencoded` should be sensible inferred default and user should be able to override it, e.g. by `multipart/form-data` or any other header of choosing.
